# Generated by Django 5.2.11 on 2026-02-17 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asha_reports', '0001_initial'),
        ('district', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ashareport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asha_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ashareport',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asha_reports', to='district.villageboundary'),
        ),
        migrations.AddField(
            model_name='waterqualityreading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality_readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
