# Generated by Django 5.2.11 on 2026-02-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashareport',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
