# Generated by Django 5.2.11 on 2026-02-17 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_reports', '0003_ashareport_is_processed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashareport',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='ashareport',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified by Doctor'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated to District'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='ashareport',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ashareport',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
